sudo: required

services: docker

bofore_install:
  - docker-compose up --build -d


script:
  - docker-compose --env 'RAILS_ENV=test' rails db:create 
  - docker-compose --env 'RAILS_ENV=test' rails db:migrate
  - docker-compose --env 'RAILS_ENV=test' rails test